services:
  # 1. Banco de Dados PostgreSQL
  db:
    image: postgres:15
    container_name: joias_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=joias_db
      - POSTGRES_USER=joias_user
      - POSTGRES_PASSWORD=joias_password
    ports:
      - "5432:5432"

  # 2. Backend (API Django)
  api:
    build: ./backend
    container_name: joias_backend
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - SECRET_KEY=sua-chave-secreta-aqui
      - DEBUG=True
      - ALLOWED_HOSTS=*
      # Configuração do Banco para usar o container 'db'
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=joias_db
      - DB_USER=joias_user
      - DB_PASSWORD=joias_password
      - DB_HOST=db
      - DB_PORT=5432
      # Permite o Frontend acessar a API
      - CORS_ALLOWED_ORIGINS=http://localhost:3000

  # 3. Frontend (Next.js)
  web:
    build: ./frontend
    container_name: joias_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules # Evita apagar a pasta node_modules do container
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - api

volumes:
  postgres_data: